#!/usr/bin/env bash

has_tuigreet=0

# Check the dependency return false if installed dependency
function check_dep() {
    command -v tuigreet >/dev/null 2>&1 && has_tuigreet=1
    return $has_tuigreet
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        [[ $has_tuigreet -ne 1 ]] && {
            run paru -S greetd-tuigreet
        }
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ $sys_id == "hydrogen" ]]; then
        run sudo mkdir -p /etc/greetd
        run sudo ln -sfn $rootdir/item/tuigreet/src/config.toml /etc/greetd/config.toml
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return false if installed
function check() {
    [[ -f /etc/greetd/config.toml ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    if [[ $sys_id == "hydrogen" ]]; then
        run sudo rm /etc/greetd/config.toml
    else
        log_error "No default uninstall method is set"
        return 1
    fi
}
