#!/usr/bin/env bash

# Check the dependency return false if installed dependency
function check_dep() {
    command -v bat 1>/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        run brew install bat
        return 0
    fi
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S bat
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    file=$(bat --config-file)
    dir=$(bat --config-dir)
    run mkdir -p $dir/themes
    find ~/.config/bat/themes/ -name 'Catppuccin.*.tmTheme' | grep . || {
        [[ -d /tmp/catppuccin-bat ]] || run git clone --depth 1 https://github.com/catppuccin/bat.git /tmp/catppuccin-bat
        # File name has space inside
        run rsync -a /tmp/catppuccin-bat/themes/ $dir/themes/
        run bat cache --build
    }
    run ln -sfn $rootdir/items/bat/src/bat.conf $file
}

# Check if the item is installed, return false if installed
function check() {
    command -v bat 1>/dev/null 2>&1 || return 1
    dir=$(bat --config-dir)
    [[ -d $dir ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    dir=$(bat --config-dir)
    run rm -rf $dir
}
