#!/usr/bin/env bash

CONFIG_PATH=$HOME/.config/tlrc/config.toml

# Check the dependency return false if installed dependency
function check_dep() {
    command -v tldr >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        run brew install tlrc
        return $(( $? ))
    fi

    case "$sys_id" in
        "hydrogen")
            run paru -S tlrc-bin
            return $(( $? ))
            ;;
        "lithium")
            log_error "No default installation method is set, not implemented"
            return 1
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    run mkdir -p $(dirname "$CONFIG_PATH")
    run ln -sfn $rootdir/items/tlrc/src/config.toml "$CONFIG_PATH"
}

# Check if the item is installed, return false if installed
function check() {
    [[ -f $CONFIG_PATH ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf $(dirname "$CONFIG_PATH")
}
