#!/usr/bin/env bash

[[ $(uname) == "Darwin" ]] || {
    log_error "You cannot install paperwm.spoon on non-macos system"
    exit 1
}

has_hammer=0
has_paperwm=0

# Check the dependency return false if installed dependency
function check_dep() {
    mdfind "kMDItemFSName == '*.app'" | grep Ghostty 2>/dev/null 1>&2 && has_hammer=1
    [[ -d ~/.hammerspoon/Spoons/PaperWM.spoon ]] && has_paperwm=1
    return $(( !$has_hammer || !$has_paperwm ))
}

# Things to do to install the dependency
function install_dep() {
    [[ $has_hammer -ne 0 ]] || run brew install hammerspoon
    [[ $has_paperwm -ne 0 ]] || run git clone https://github.com/mogenson/PaperWM.spoon ~/.hammerspoon/Spoons/PaperWM.spoon
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/paperwm/src/init.lua $HOME/.hammerspoon/init.lua
}

# Check if the item is installed, return false if installed
function check() {
    [[ -f $HOME/.hammerspoon/init.lua ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf $HOME/.hammerspoon/init.lua
}
