#!/usr/bin/env bash

declare -A DEPS=(
    [libawaita-patch]="libadwaita-without-adwaita"
    [theme-switcher]="darkman"
    [icon]="whitesur-icon-theme-git"
    [cursor-theme]="bibata-cursor-theme-bin"
    [theme-dark]="catppuccin-gtk-theme-git"
)

declare -A HAS

# Check the dependency return true if installed dependency
function check_dep() {
    if [ $(uname) != "Linux" ]; then
        log_error "Cannot install gtk theme on a non-linux system"
        return 1
    fi
    local all_ok=1
    if [[ $sys_id == "archlinux" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]}"
            if pacman -Q "$pkg" >/dev/null 2>&1; then
                HAS[$dep]=1
            else
                HAS[$dep]=0 
                all_ok=0
                log_hint "'$dep' provided by package '$pkg' not installed"
            fi
        done
        return $all_ok
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]}"
            [[ ${HAS[$dep]} -eq 0 ]] && run paru -S "$pkg"
        done
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p $HOME/.local/share
    run ln -sfn $rootdir/items/gtk-theme/src/dark-mode.d $HOME/.local/share/dark-mode.d
    run ln -sfn $rootdir/items/gtk-theme/src/light-mode.d $HOME/.local/share/light-mode.d
    run mkdir -p $HOME/.config/gtk-theme.d/settings
    run "[[ -f $HOME/.config/gtk-theme.d/settings/theme-dark ]] || echo 'Catppuccin-Lavender-Dark' > $HOME/.config/gtk-theme.d/settings/theme-dark"
    run "[[ -f $HOME/.config/gtk-theme.d/settings/theme-light ]] || echo 'Catppuccin-Lavender-Light' > $HOME/.config/gtk-theme.d/settings/theme-light"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d $HOME/.config/gtk-theme.d || -d $HOME/.local/share/{light,dark}-mode.d ]] && return 0
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf $HOME/.config/gtk-theme.d $HOME/.local/share/{light,dark}-mode.d
}
