#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v xmake >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S xmake
    elif [[ $sys_id == "helium" ]]; then
        run brew install xmake
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ ! -d /tmp/catppuccin-xmake ]];then
        run git clone https://github.com/0komo/catppuccin-xmake.git /tmp/catppuccin-xmake
    fi
    run mkdir -p $HOME/.xmake
    run cp -r /tmp/catppuccin-xmake/themes $HOME/.xmake/
}

# Check if the item is installed, return true if installed
function check() {
    ls -a $HOME/.xmake/themes/ | grep "catppuccin_.*" >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf $HOME/.xmake/themes/catppuccin_*
}
