#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    # No dependency
    return 1
}

# Things to do to install the dependency
function install_dep() {
    # No dependency
    :;
}

# Things to do to install the item
function install() {
    log_info "Installing 'Nord' theme for fcitx5..."
    run git clone https://github.com/tonyfettes/fcitx5-nord.git /tmp/fcitx5-nord
    run mkdir -p ~/.local/share/fcitx5/themes/
    run cp -r /tmp/fcitx5-nord/Nord-* ~/.local/share/fcitx5/themes/

    log_info "Installing 'Tokyonight' theme for fcitx5..."
    run git clone https://github.com/ch4xer/fcitx5-Tokyonight.git
    run mkdir -p ~/.local/share/fcitx5/themes/ /tmp/fcitx5-tokyonight
    run cp -r /tmp/fcitx5-tokyonight/Tokyonight-* ~/.local/share/fcitx5/themes/
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d $HOME/.local/share/fcitx5/themes/Nord-Dark ]] && 
    [[ -d $HOME/.local/share/fcitx5/themes/Nord-Light ]] && 
    [[ -d $HOME/.local/share/fcitx5/themes/Tokyonight-Day ]] && 
    [[ -d $HOME/.local/share/fcitx5/themes/Tokyonight-Storm/ ]] &&  return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    [[ -d $HOME/.local/share/fcitx5/themes/ ]] && run rm -rf $HOME/.local/share/fcitx5/themes/Tokyonight-* $HOME/.local/share/fcitx5/themes/Nord-*
}
