#!/usr/bin/env bash
presets["linux_basic"]="alacritty bash zsh fastfetch tmux yazi nvim nvim.vscode"
presets["macmini"]="bash btop fastfetch ghostty karabiner kitty lsd nvim nvim.vscode tmux wezterm yazi zsh"
presets["hypr"]="hyprland kitty rofi waybar"
presets["niri"]="alacritty anyrun bash btop fish fastfetch fcitx5-theme gnome-setting gtk-theme imv hyprlock lsd mpv nvim niri waybar swaync tmux wlogout yazi zathura zsh"

paru_flags="--noconfirm --skipreview"

pacman_opt="--noconfirm"

brew_flags=""

function paru() {
    command paru $paru_flags "$@"
}

function pacman() {
    command pacman $pacman_opt "$@"
}

function brew() {
    command brew $brew_flags "$@"
}
