presets["linux_basic"]="alacritty bash zsh fastfetch tmux yazi nvim nvim.vscode"
presets["extras_cli"]="btop lsd"
presets["extras_gui"]="ghostty wezterm"
presets["darwin_basic"]="karabiner"
presets["hyprwm"]="hyprland kitty rofi waybar"
