#!/usr/bin/env bash

declare -A DEPS=(
    # [name]="packname"
    [niri]="niri"
    [portal-gtk]="xdg-desktop-portal-gtk"
    [portal-gnome]="xdg-desktop-portal-gnome"
    [icon]="whitesur-icon-theme-git"
    [cursor-theme]="bibata-cursor-theme-bin"
    [theme-dark]="catppuccin-gtk-theme-git"
    [qt-theme]="qt6ct-kde"
    [wallpaper-engine]="swww"
    [bluetooth-panel]="blueberry-wayland"
    [wifi-panel]="network-manager-applet"
    [system-font]="ttf-lxgw-wenkai"
    [system-font-lite]="ttf-lxgw-wenkai-mono-lite"
    [mono-nerd-font]="maple-mono-nf-cn"
    # for wallpaper converting
    [ffmpeg]="ffmpeg"
    [fzf]="fzf"
    [image-viewer]="imagemagick"
    [volume-panel]="pavucontrol"
    [theme-switcher]="darkman"
)

declare -A HAS

# Check the dependency return true if installed dependency
function check_dep() {
    if [ $(uname) != "Linux" ]; then
        log_error "Cannot install niri on a non-linux system"
        return 1
    fi
    local all_ok=1
    if [[ $sys_id == "archlinux" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]}"
            if pacman -Q "$pkg" >/dev/null 2>&1; then
                HAS[$dep]=1
            else
                HAS[$dep]=0 
                all_ok=0
                log_hint "'$dep' provided by package '$pkg' not installed"
            fi
        done
        return $(( !$all_ok ))
    else
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]}"
            [[ ${HAS[$dep]} -eq 0 ]] && run paru -S "$pkg"
        done
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p $HOME/.config/niri
    run mkdir -p $HOME/.local/bin
    run ln -sfn $rootdir/items/niri/src/config.kdl ~/.config/niri/config.kdl
    run ln -sfn $rootdir/items/niri/src/Xresources ~/.Xresources
    run ln -sfn $rootdir/items/niri/src/scripts ~/.config/niri/scripts
    run ln -sfn $rootdir/assets/wallpapers ~/.config/niri/wallpapers
    run ln -sfn $rootdir/items/niri/src/scripts/fzf-clip.sh ~/.local/bin/fzf-clip
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/niri ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/niri
    run rm ~/.local/bin/fzf-clip
    run rm ~/.Xresources
}
