#!/usr/bin/env bash

# Check the dependency return false if installed dependency
function check_dep() {
    [[ $(uname) != "Linux" ]] && {
        log_error "Not linux system"
        return 1
    }
    if [[ $sys_id == "archlinux" ]]; then
        pacman -Qs "^qt6ct-kde$" >/dev/null 2>&1 || return 1
        return 0
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    [[ $(uname) != "Linux" ]] && {
        log_error "Not linux system"
        return 1
    }
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S qt6ct-kde
        return $?
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    [[ $(uname) != "Linux" ]] && {
        log_error "Not linux system"
        return 1
    }
    if [[ $sys_id == "archlinux" ]]; then
        run mkdir -p $HOME/.local/share/color-schemes 
        run "curl -fsSL https://github.com/catppuccin/kde/releases/download/v0.2.6/Macchiato-color-schemes.tar.gz | tar xzf - -C $HOME/.local/share/color-schemes/"
        return $?
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return false if installed
function check() {
    local matches=( "$HOME"/.local/share/color-schemes/CatppuccinMacchiato*.colors )
    return $(( ${#matches[@]} == 16 ))
}

# Things to do to uninstall the item
function uninstall() {
    run rm "$HOME"/.local/share/color-schemes/CatppuccinMacchiato*.colors
}
