#!/usr/bin/env bash

# NOTE: Discord patch for niri/hyprland

# Check the dependency return true if installed dependency
function check_dep() {
    if [ $(uname) != "Linux" ]; then
        log_error "Cannot install discord on os except linux"
        return 1
    fi
    command -v vesktop 1>/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    run paru -S vesktop-bin
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/discord/src/vesktop.desktop ~/.local/share/applications/vesktop.desktop
}

# Check if the item is installed, return true if installed
function check() {
    [[ -f $HOME/.local/share/applications/vesktop.desktop ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm ~/.local/share/applications/vesktop.desktop
}
