# ---------------------------- Kali Prompt--------------------------------
# VIRTUAL_ENV_DISABLE_PROMPT=1
# prompt_symbol=@
# PROMPT=$'
# %F{%(#.blue.green)}┌──${debian_chroot:+($debian_chroot)─}${VIRTUAL_ENV:+($(basename $VIRTUAL_ENV))─}(%B%F{%(#.red.blue)}%n'$prompt_symbol$'%m%b%F{%(#.blue.green)})─[%B%F{reset}%(6~.%-1~/…/%4~.%5~)%b%F{%(#.blue.green)}]$(git_prompt_info) $(git_remote_status)\n└─%B%(#.%F{red}#.%F{blue}$)%b%F{reset} '
# 
# ZSH_THEME_GIT_PROMPT_PREFIX="-<%{$reset_color%}%{$fg[white]%}%{$fg_bold[blue]%}"
# ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}%{$fg[green]%}>"
# ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}x%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_BEHIND_REMOTE="%{$fg_bold[magenta]%}↓%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_AHEAD_REMOTE="%{$fg_bold[magenta]%}↑%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_DIVERGED_REMOTE="%{$fg_bold[magenta]%}↕%{$reset_color%}"
# 
# unset prompt_symbol
# ---------------------------- Kali Prompt--------------------------------

# Kali prompt improved
# ┌──(venv)-(username@hostname)─[~]-<branch* 114+10^514- x!> ↑
# └─$                                               --INSERT--

format = '''
[┌─${custom.virtual}─\($username[@](blue bold)$hostname\)─\[${custom.directory}\]$git_branch$git_status](green)
[└─](green)[\$ ](blue bold)'''

# Vi mode, for zsh/fish
right_format = """
$character\
"""

[username]
show_always = true
format      = '[$user]($style)'
style_user  = "blue bold"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style  = "blue bold"

[git_branch]
format = '─<[$branch]($style)'
style  = 'blue bold'


[git_status]
format     = "[$modified]($style)( $staged$renamed$deleted)([ $untracked$conflict]($style))>[$ahead_behind](purple bold)"
style      = "bold red"
untracked  = "x"
modified   = "*"
conflicted = "!"
staged     = "[+$count](green)"
renamed    = "[^$count](yellow)"
deleted    = "[-$count](red)"
ahead      = " ↑"
diverged   = " ↕"
behind     = " ↓"

[custom.virtual]
command = 'basename $VIRTUAL_ENV'
format  = '─\([$output]($style)\)'
style   = 'green'
when    = 'test -n "$VIRTUAL_ENV"'

[custom.directory]
command = '~/.config/starship/scripts/path.sh'
format  = '[$output]($style)'
style   = "bold"
when    = true

[character]
format                    = "$symbol"
success_symbol            = "[--INSERT--](green)"
error_symbol              = "[--INSERT--](red)"
vimcmd_symbol             = "[--NORMAL--](blue)"
vimcmd_replace_one_symbol = "[--REPLACE ONE--](purple)"
vimcmd_replace_symbol     = "[--REPLACE--](purple)"
vimcmd_visual_symbol      = "[--VISUAL--](yellow)"
