#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v wlogout >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    run paru -S wlogout
}

# Things to do to install the item
function install() {
    items=$(bash -c "ls $rootdir/items/wlogout/src")
    run mkdir -p ~/.config/wlogout
    for item in $items; do
        run ln -sfn $rootdir/items/wlogout/src/$item ~/.config/wlogout/$item
    done
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d $HOME/.config/wlogout ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf $HOME/.config/wlogout
}
