#!/usr/bin/env bash

# Dae is a high-performance transparent proxy solution.
#
# This config provides a bunch of utilities to manage dae's configuration and subscriptions

# Check the dependency return false if installed dependency
function check_dep() {
    [[ $(uname) != "Linux" ]] && {
        log_error "You cannot install dae on non-linux"
        exit 1
    }
    ok=0
    # check kernel
# WARN: DO NOT TOUCH THE CODE ! ! APPLY LINT CAN CAUSE ERROR
KERNEL_OP=$(bash -c "(zcat /proc/config.gz || cat /boot/{config,config-$(uname -r)}) |\
grep -E 'CONFIG_(DEBUG_INFO|DEBUG_INFO_BTF|KPROBES|KPROBE_EVENTS|BPF|\
BPF_SYSCALL|BPF_JIT|BPF_STREAM_PARSER|NET_CLS_ACT|NET_SCH_INGRESS|NET_INGRESS|\
NET_EGRESS|VETH|NET_CLS_BPF|BPF_EVENTS|CGROUPS)=|# CONFIG_DEBUG_INFO_REDUCED is not set' | sort")
EXPECTED_KERNEL_OP=$(echo "CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_CGROUPS=y
CONFIG_KPROBES=y
CONFIG_NET_INGRESS=y
CONFIG_NET_EGRESS=y
CONFIG_NET_SCH_INGRESS=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_CLS_ACT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_VETH=m
CONFIG_DEBUG_INFO=y
# CONFIG_DEBUG_INFO_REDUCED is not set
CONFIG_DEBUG_INFO_BTF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_BPF_EVENTS=y" | sort)
diff -u <(echo "$EXPECTED_KERNEL_OP") <(echo "$KERNEL_OP")
# WARN: DO NOT TOUCH THE CODE ! ! APPLY LINT CAN CAUSE ERROR
    ok=$(( $ok || $? ))

    # check dae binary
    command -v dae >/dev/null 2>&1
    ok=$(( $ok || $? ))
    return $ok
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S dae
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    log_error "Not completed"
    exit 1
    if [[ $sys_id == "hydrogen" ]]; then
        items=$(bash -c "ls $rootdir/items/dae/src/scripts")
        run mkdir -p $HOME/.config/dae/template $HOME/.local/bin
        for item in $items; do
            run ln -sfn $rootdir/items/dae/scripts/$item ~/.local/bin/$item
        done
        run ln -sfn $rootdir/items/dae/templates $HOME/.config/dae/templates
        run rehash
        log_hint "Utilities are installed, including:"
        log_hint ""
        log_hint "- dae-genconf    Generate configuration file to /etc/dae"
        log_hint ""
        log_hint "Templates are at $HOME/.config/dae/templates"
        log_warn "Configuration is not deployed, you should provide subscription link"
        log_warn "or node lists yourself, and run scripts"
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return false if installed
function check() {
    [[ -d $HOME/.config/dae && !$(command -v dae-genconf >/dev/null 2>&1) ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    items=$(bash -c "ls $rootdir/items/dae/src/scripts")
    for item in $items; do
        run rm $HOME/.local/bin/$item
    done
    run rm -rf $HOME/.config/dae
}
