$terminal       = alacritty
$fileManager    = dolphin
$menu           = $scripts/rofi/launch.sh drawer
$fileTerminal   = alacritty -e yazi
$launch         = pkill -x anyrun || anyrun
$lock           = hyprlock
$setting        = (cd ~/.config/hypr && neovide hyprland.conf)
$screenshot     = hyprshot -m active
$supershot      = $scripts/screenshot
$browser        = firefox
$notification   = swaync-clent -t

xwayland {
    force_zero_scaling = true
}
