#!/usr/bin/env bash

# NOTE: Patch .gitconfig and set delta as default pager

# Check the dependency return false if installed dependency
function check_dep() {
    command -v delta >/dev/null 2>&1 || return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        run brew install git-delta
    elif [[ $(uname) == "Linux" && $sys_id == "hydrogen" ]]; then
        run paru -S git-delta
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run git config --global core.pager delta
    run git config --global interactive.diffFilter 'delta --color-only'
    run git config --global delta.navigate true
    run git config --global delta.side-by-side true
    run git config --global delta.dark true
    run git config --global merge.conflictStyle zdiff3
    run mkdir -p $HOME/.config/delta/themes/
    run "curl -fsSL https://github.com/catppuccin/delta/raw/refs/heads/main/catppuccin.gitconfig > $HOME/.config/delta/themes/catppuccin.gitconfig"
    run git config --global --add include.path ~/.config/delta/themes/catppuccin.gitconfig
    run git config --global delta.features 'catppuccin-mocha'
}

# Check if the item is installed, return false if installed
function check() {
    [[ $(git config --get core.pager 2>/dev/null) == "delta" ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    :;
}
