#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    pacman -Q gnome-control-center &>/dev/null && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S gnome-control-center
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ $sys_id == "archlinux" ]]; then
        run mkdir -p ~/.local/share/applications/
        run cp $rootdir/items/gnome-setting/src/gnome-control-center.desktop ~/.local/share/applications/gnome-control-center.desktop
        run mkdir -p ~/.local/share/scripts
        run ln -sfn $rootdir/items/gnome-setting/src/settings.sh ~/.local/share/scripts/settings.sh
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -f ~/.local/share/scripts/settings.sh && -f ~/.local/share/applications/gnome-control-center.desktop ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm ~/.local/share/applications/gnome-control-center.desktop
    run rm ~/.local/share/scripts/settings.sh
}
