#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v yazi >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S yazi
    elif [[ $sys_id == "macmini" ]]; then
        run brew install yazi
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/yazi
    run ln -sfn $rootdir/items/yazi/src/themes ~/.config/yazi/themes
    run ln -sfn $rootdir/items/yazi/src/yazi.toml ~/.config/yazi/yazi.toml
    log_hint "please run 'ln -sf ~/.config/yazi/themes/<theme>.toml ~/.config/yazi/theme.toml' to choose a theme"
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/yazi ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/yazi
}
