#!/usr/bin/env bash

# Check the dependency return false if installed dependency
function check_dep() {
    command -v keyd || return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    case "$sys_id" in
        "hydrogen")
            run paru -S keyd
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    case "$sys_id" in
        "hydrogen")
            run sudo mkdir -p /etc/keyd/
            run sudo cp "$item_dir/src/default.conf" /etc/keyd/default.conf
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Check if the item is installed, return false if installed
function check() {
    [[ -d /etc/keyd ]] || return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    case "$sys_id" in
        "hydrogen")
            run sudo rm -rf /etc/keyd/
            ;;
        *)
            log_error "No default uninstallation method is set"
            return 1
            ;;
    esac
}
