#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        if command -v hyprland >/dev/null 2>&1; then
            return 0
        else
            log_hint "Hyprland not installed"
            return 1
        fi
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [ $(uname) != "Linux" ]; then
        log_error "Cannot install hyprland on a non-linux system"
        return 1
    fi
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S hyprland hyprlock
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/hyprland/src ~/.config/hypr
}

# Check if the item is installed, return true if installed
function check() {
    [[ -L ~/.config/hypr ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/hypr
}
