osc=no

http-proxy="http://127.0.0.1:2080"

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no

[bilibili-add-referrer]
profile-restore = copy
profile-cond = path:match("https://www.bilibili.com")~=nil
referrer = https://www.bilibili.com/

[extension.gif]
interpolation=no
loop-file=inf
