#!/usr/bin/env bash

# NOTE: Element patch for niri/hyprland

# Check the dependency return true if installed dependency
function check_dep() {
    command -v element-desktop 1>/dev/null 2>&1 && return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    run paru -S element-desktop
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/matrix/src/io.element.Element.desktop ~/.local/share/applications/io.element.Element.desktop
}

# Check if the item is installed, return true if installed
function check() {
    [[ -f $HOME/.local/share/applications/io.element.Element.desktop ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm $HOME/.local/share/applications/io.element.Element.desktop
}
