#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v btop >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    run brew install btop
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/btop/src ~/.config/btop
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/btop
}
