# List of plugins
set -g @plugin 'tmuxpack/tpack'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Color settings, underline and undercurl
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# reindex when window delete
set -g renumber-windows

# Clipboard settings
set-option -g set-clipboard     on
# set-option -g allow-passthrough on
set-option -g update-environment "SSH_TTY SSH_CONNECTION DISPLAY"

# Ensure focus-events settings for im-switching on nvim
set -g focus-events on

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""

# Session prompt
SESSION_ICON="Session: "
SESSION_COLOR="#{?client_prefix,#[fg=#94e2d5],#[fg=#89b4fa]}#{?client_prefix,#[bold],}"
SESSION_TEXT="#S"
set -g status-right "#(echo  '${SESSION_COLOR}${SESSION_ICON}${SESSION_TEXT}')"

# Status line banner
set-option -g status-position bottom
set -g status-style 'bg=None,fg=#{@on_surface}'

# Pane border
set -g pane-border-style 'fg=#a6adc8'
# set -g pane-active-border-style 'fg=#f5e0dc'
set -g pane-active-border-style 'fg=#b4beff,bold'
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-border-lines single

# Pane border status
# set -g pane-border-format "[#{client_prefix,#[fg=#94e2d5],#[fg=#89b4fa]}#{?pane_active,#[bold],} #P #[fg=default,nobold]]"
set -g pane-border-format "[#{?pane_active,#[fg=#b4beff],#[fg=default]}#{?pane_active,#[bold],} #P #[fg=default,nobold]]"
setw -g pane-border-lines single

# Auto hide pane-border-status line when only one pane is displayed
set-hook -g 'after-new-session'  'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-new-window'   'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-kill-pane'    'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'pane-exited'        'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-split-window' 'run-shell -b "if [ \#{window_panes} -gt 1 ]; then tmux set pane-border-status top; fi"'

# Window tab
set -g window-status-format '#[fg=#89b4fa] #{window_index} #W#{?window_zoomed_flag,  , }'
set -g window-status-current-format '#[fg=#94e2d5,bold] [#{window_index} #W#{?window_zoomed_flag,  ,}]'

set -g message-command-style 'bg=#1e1e2e,fg=#cdd6f4'
set -g message-style 'bg=#1e1e2e,fg=#cdd6f4'

set -g mode-style 'bg=#f5e0dc,fg=#1e1e2e'

set -g popup-border-lines rounded
set -g popup-border-style "fg=blue"

# Set window start path
unbind c
unbind %
unbind '"'
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# scrollback mode
unbind [
bind [ display-popup -w 90% -h 90% -E \
"tmux capture-pane -pJS - \
| perl -0777 -pe 's/\\n+\\z/\\n\\n/' \
| nvim -R -c 'set filetype=scrollback' -"

# history limit
set -g history-limit 10000

# Key mappings
unbind C-b
set -g prefix C-Space

# Mouse enable
set -g mouse on

# Visual Mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v   send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y   send-keys -X copy-selection-and-cancel

source-file ~/.config/tmux/local.conf
