#!/usr/bin/env bash

# How to localize

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ -d ~/.oh-my-zsh ]]; then
        return 1
    else
        return 0
    fi
    return 0
}

# Things to do to install the dependency
function install_dep() {
    run sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    :;
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/zsh/src/zsh.conf ~/.zshrc
    if [[ ! -f ~/.oh-my-zsh/custom/themes/kali.zsh-theme ]]; then
        log_warn "Theme not installed, installing..."
        run ln -sf $rootdir/items/zsh/src/assets/kali.zsh-theme ~/.oh-my-zsh/custom/themes/kali.zsh-theme
    fi
    case "$sys_id" in
        # Localize?
        "archlinux")
            ;;
        *)
            log_warn "Not assigned a system_id, some localized config maynot be installed"
            ;;
    esac
    :;
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -f ~/.zshrc ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    :;
}
