--bind-try $HOME/Documents/  $HOME/Documents/  
--bind-try $HOME/Desktop/    $HOME/Desktop/    
--bind-try $HOME/Pictures/   $HOME/Pictures/   
--bind-try $HOME/Videos/     $HOME/Videos/     
--bind-try $HOME/Data/       $HOME/Data/     
--bind-try $HOME/Workspace/  $HOME/Workspace/
