# ZSH_THEME="kali"
source ~/.zsh/modules/plugin.sh
source ~/.zsh/modules/env.sh
source ~/.zsh/modules/alias.sh
source ~/.zsh/modules/function.sh
source ~/.zsh/modules/misc.sh
# Source platform related code
source ~/.zsh/localize.conf
# Source temporary code
[[ -f $HOME/.zsh/extras.sh ]] && source $HOME/.zsh/extras.sh
# Safe load starship
[[ -z $STARSHIP_LOADED ]] && {
    eval "$(starship init zsh)"
    STARSHIP_LOADED=1
}
