#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v fastfetch >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S fastfetch
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    items=$(bash -c "ls $rootdir/items/fastfetch/src")
    run mkdir -p ~/.config/fastfetch
    for item in $items; do
        run ln -sfn $rootdir/items/fastfetch/src/$item ~/.config/fastfetch/$item
    done
    log_hint "please run 'ln -sf ~/.config/fastfetch/<theme>.jsonc ~/.config/fastfetch/config.jsonc' to choose a theme"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/fastfetch ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/fastfetch/
}
