#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v fish >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S fish
        return $(( $? ))
    elif [[ $sys_id == "helium" ]]; then
        run brew install fish
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/fish/src ~/.config/fish
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/fish || -L ~/.config/fish ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/fish
}
