#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v fish >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    case "$sys_id" in
        hydrogen)
            run paru -S fish
            ;;
        helium)
            run brew install fish
            ;;
        lithium)
            run apt install fish
            ;;
        *)
            log_error "No default installation method"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    run mkdir -p $HOME/.config/fish/{completions,conf.d,functions}

    for item in $item_dir/common/completions/*; do
        local name=$(basename "$item")
        run ln -sfn $item $HOME/.config/fish/completions/$name
    done

    for item in $item_dir/common/functions/*; do
        local name=$(basename "$item")
        run ln -sfn $item $HOME/.config/fish/functions/$name
    done

    for item in $item_dir/common/conf.d/*; do
        local name=$(basename "$item")
        run ln -sfn $item $HOME/.config/fish/conf.d/$name
    done

    run ln -sfn $item_dir/common/config.fish $HOME/.config/fish/config.fish

    if [[ ! -f $item_dir/local/conf/$sys_id.fish ]]; then
        log_error "Cannot find a local.fish"
        run touch $item_dir/local/conf/$sys_id.fish
    fi
    run ln -sfn $item_dir/local/conf/$sys_id.fish $HOME/.config/fish/conf.d/99-local.fish

    if [[ -d $item_dir/local/func/$sys_id ]]; then
        for item in $item_dir/local/func/$sys_id/*; do
            local name=$(basename "$item")
            run ln -sfn $item $HOME/.config/fish/functions/$name
        done
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/fish || -L ~/.config/fish ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/fish
}
