#!/usr/bin/env bash

# Localization
alias z="zathura"
alias pdb="python -m pdb"
alias open="xdg-open"
alias alacritty-config="vi ~/.config/alacritty/alacritty.toml && alacritty migrate"
alias gdb-config="vi ~/.gdbinit"
alias docker-start="sudo systemctl start docker.socket && sudo systemctl status docker.socket "
alias docker-status="systemctl status docker.socket"
alias docker-stop="sudo systemctl stop docker.socket && sudo systemctl status docker.socket"
alias mvi='mpv --config-dir=$HOME/.config/mvi'
alias grep='rg'
alias cat='/usr/bin/bat'
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

export STARSHIP_CONFIG=~/.config/starship/kali.toml
export PATH="/home/aurora/.local/bin:$PATH:/home/aurora/.cargo/bin"

fcp() {
    if [[ $# -eq 0 ]]; then
        echo "Copy a file to clipboard"
        echo "Usage: fcp <options> <path_to_file>"
        echo "Options:"
        echo "-bin      Copy content instead of uri"
        return 1
    fi
    file=""
    bin=0
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -bin)
                bin=1
                shift
                ;;
            --)
                shift
                [[ $# -gt 1 ]] && {
                    echo "Warning: copy multiple file, only the last one enter clipboard"
                    while [[ $# -gt 1 ]]; do
                        shift
                    done
                }
                file="$1"
                break
                ;;
            -*)
                echo "Warning: unknown option $1...ignored"
                shift
                ;;
            *)
                [[ -z "$file" ]] || {
                    echo "Warning: copy multiple file, only the last one enter clipboard"
                }
                file="$1"
                shift
                ;;
        esac
    done
    [[ $bin -eq 1 ]] || {
        wl-copy --type text/uri-list "file://$(realpath -- $file)"
        return $?
    }
    cat -- "$file" | wl-copy
}

jp() {
    target=$(grep -oP '^:[0-9: ]*;\s*cd\s*\K(/[^ ]*|~[^ ]*)' ~/.zsh_history | fzf)
    [[ -n $target ]] && eval "cd $target"
}

sort_packages() {
    if [[ $# -ne 0 ]]; then
        echo "List and sort the packages"
        echo ""
        echo "Usage: $0"
        return 1
    fi
    LC_ALL=C.UTF-8 pacman -Qeti |
      awk '
    /^Name/{
      name=$3
    }

    /^Description/ {
      for(i=3; i<NF; i++)
        dis = dis $i " "
      dis = dis $NF
    }

    /^Installed Size/ {
      print $4 substr($5,1,1), "\x1b[31m"name"\x1b[0m" "\0" "\x1b[32m"dis"\0\x1b[0m"
      dis=""
    }' |
      sort -h |
      tr "\0" "\n" |
      less -R
}

# pnpm
export PNPM_HOME="/home/aurora/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
