#!/usr/bin/env bash

# Localization
alias z="zathura"
alias pdb="python -m pdb"
alias open="xdg-open"
alias alacritty-config="vi ~/.config/alacritty/alacritty.toml && alacritty migrate"
alias gdb-config="vi ~/.gdbinit"
alias docker-start="sudo systemctl start docker.socket && sudo systemctl status docker.socket "
alias docker-status="systemctl status docker.socket"
alias docker-stop="sudo systemctl stop docker.socket && sudo systemctl status docker.socket"
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

export STARSHIP_CONFIG=~/.config/starship/kali.toml
export PATH="/home/aurora/.local/bin:$PATH:/home/aurora/.cargo/bin"

fcp() {
    if [[ $# -eq 0 ]]; then
        echo "Copy a file to clipboard"
        echo "Usage: fcp <path_to_file>"
        return 1
    fi
    wl-copy --type text/uri-list "file://$(realpath $1)"
}

jp() {
    target=$(grep -oP '^:[0-9: ]*;\s*cd\s*\K(/[^ ]*|~[^ ]*)' ~/.zsh_history | fzf)
    [[ -n $target ]] && eval "cd $target"
}
