#!/usr/bin/env bash
# Localization
alias zat="zathura"
alias pdb="python -m pdb"
alias open="xdg-open"
alias alacritty-config="vi ~/.config/alacritty/alacritty.toml && alacritty migrate"
alias gdb-config="vi ~/.gdbinit"
alias objdump="/usr/bin/objdump --disassembler-color=on -M intel"
alias docker-start="sudo systemctl start docker.socket && sudo systemctl status docker.socket "
alias docker-status="systemctl status docker.socket"
alias docker-stop="sudo systemctl stop docker.socket && sudo systemctl status docker.socket"
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

export STARSHIP_CONFIG=~/.config/starship/kali.toml
