#!/usr/bin/env bash

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export PATH="/opt/homebrew/bin:/opt/homebrew/opt/rustup/bin:/opt/homebrew/opt/llvm@20/bin:\
$PATH:/Users/qingfengzl/.local/bin:/Users/qingfengzl/.cargo/bin"
# export PATH=/opt/homebrew/bin:/opt/homebrew/opt/rustup/bin:$PATH

export PATH="$PATH:/Volumes/SamsungSSD_Data/projects/texpresso/build"

export STARSHIP_CONFIG=~/.config/starship/kali.toml

export LLVM_HOME="/opt/homebrew/opt/llvm"
export RUSTFLAGS="$RUSTFLAGS -A dead_code"

alias z=zathura

function fcp {
    osascript -e "set the clipboard to (POSIX file \"$(realpath "$1")\")"
}

function clear_ds_store {
    local recursive=0
    local verbose=0
    local dryrun=0
    local paths=()

    for arg in "$@"; do
        case "$arg" in
            -r|--recursive)
                recursive=1
                ;;
            -v|--verbose)
                verbose=1
                ;;
            -n|--dry-run)
                dryrun=1
                ;;
            -h|--help)
                echo "Delete the .DS_Store dirs"
                echo "Usage clear_ds_store [options] [dirs]"
                echo "-h    --help      Print this help and exit"
                echo "-r    --recursive Recursively delete '.DS_Store' in given path(s)"
                echo "-n    --dry-run   Print the position of '.DS_Store's to delete BUT DO NOTHING"
                echo "-v    --verbose   Print the position of '.DS_Store's to delete WHILE DOING THE JOB"
                return 0
                ;;
            -*)
                echo "Unknown Option: $arg" >&2
                return 1
                ;;
            *)
                paths+=("$arg")
                ;;
        esac
    done

    # default path is `.`
    if (( ${#paths[@]} == 0 )); then
        paths=(.)
    fi

    for dir in "${paths[@]}"; do
        local find_opts=()
        find_opts+=("$dir")
        (( recursive )) || find_opts+=(-maxdepth 1)
        find_opts+=(-type f -name ".DS_Store")

        while IFS= read -r pos; do
            if (( dryrun )); then
                echo "[dry-run] $pos"
            else
                if (( verbose )); then
                    echo "Deleted: $pos"
                fi
                rm -rf "$pos"
            fi
        done < <(find "${find_opts[@]}")
    done
}
