#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v kitty >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run sudo pacman -S kitty
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/kitty/src ~/.config/kitty
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/kitty ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run [[ -L ~/.config/kitty ]] && unlink ~/.config/kitty 
}
