#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        mdfind "kMDItemFSName == '*.app'" | grep kitty 2>/dev/null 1>&2
        return $(( !$? ))
    elif [[ $(uname) == "Linux" ]]; then
        command -v kitty >/dev/null 2>&1
        return $(( !$? ))
    else
        log_error "Unsupported system"
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S kitty
        return $(( $? ))
    elif [[ $sys_id == "macmini" ]]; then
        run brew install kitty
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ $(command -v zsh >/dev/null 2>&1) -ne 0 ]]; then
        log_error "Cannot install kitty config without zsh binary installed"
        return 1
    fi
    run mkdir -p ~/.config/kitty
    run ln -sf $rootdir/items/kitty/src/current-theme.conf ~/.config/kitty/current-theme.conf
    if [[ $sys_id == "macmini" ]]; then
        log_info "Generating final config with template"
        run 'gawk -f $rootdir/utils/replace.awk $rootdir/items/kitty/local/macmini.awk $rootdir/items/kitty/src/kitty.conf.tmpl > ~/.config/kitty/kitty.conf'
    elif [[ $sys_id == "archlinux" ]]; then
        run 'awk -f $rootdir/utils/replace.awk $rootdir/items/kitty/local/archlinux.awk $rootdir/items/kitty/src/kitty.conf.tmpl > ~/.config/kitty/kitty.conf'
    else
        log_error "Haven't assigned a localized file"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/kitty ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/kitty
}
