#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    return 1
}

# Things to do to install the dependency
function install_dep() {
    :;
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/nvim.vscode/autoload
    run mkdir -p ~/.config/nvim.vscode/plugged
    run cp $rootdir/items/nvim.vscode/src/init.vim ~/.config/nvim.vscode/
    run cp $rootdir/items/nvim.vscode/src/plug.vim ~/.config/nvim.vscode/autoload/
    log_hint "Please run 'nvim -u ~/.config/nvim.vscode/plug.vim' to install plugins"
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/nvim.vscode ]]; then
        return 1;
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/nvim.vscode
}
