#!/usr/bin/env bash

has_nvim=0

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v nvim >/dev/null 2>&1; then
        has_nvim=1
    else
        log_hint "Nvim not installed"
    fi
    [[ $has_nvim -eq 1 ]] && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S nvim
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/nvim.vscode/autoload
    run mkdir -p ~/.config/nvim.vscode/plugged
    [[ -d /tmp/vim-plug ]] || run git clone --branch master --depth 1 https://github.com/junegunn/vim-plug.git /tmp/vim-plug
    run cp $rootdir/items/nvim.vscode/src/init.vim ~/.config/nvim.vscode/
    if [[ -f /tmp/vim-plug/plug.vim ]]; then
        run cp /tmp/vim-plug/plug.vim ~/.config/nvim.vscode/autoload/
    else
        log_error "Cannot find 'plug.vim', exiting..."
        return 1
    fi
    log_hint "Please run 'nvim -u ~/.config/nvim.vscode/plug.vim' to install plugins"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/nvim.vscode ]] && return 0
    return 1;
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/nvim.vscode
}
