#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v starship >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S starship
    elif [[ $sys_id == "macmini" ]]; then
        run brew install starship
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/starship
    run ln -sf $rootdir/items/starship/src/zsh.toml ~/.config.toml
    run ln -sf $rootdir/items/starship/src/zsh.toml ~/.config/starship/zsh.toml
    run ln -sf $rootdir/items/starship/src/bash.toml ~/.config/starship/bash.toml
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -L ~/.config/starship.toml || -f ~/.config/starship.toml ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/starship/zsh.toml
    run unlink ~/.config/starship/bash.toml
    run unlink ~/.config/starship/scripts/path.sh
    run unlink ~/.config/starship.toml
}
