#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v starship >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    case "$sys_id" in
        "hydrogen")
            run paru -S starship
            return $(( $? ))
            ;;
        "helium")
            run brew install starship
            return $(( $? ))
            ;;
        "lithium")
            run apt install starship
            return $(( $? ))
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/starship/scripts
    run ln -sf $rootdir/items/starship/src/scripts/path.sh ~/.config/starship/scripts/path.sh
    run ln -sf $rootdir/items/starship/src/kali.toml ~/.config/starship.toml
    run ln -sf $rootdir/items/starship/src/kali.toml ~/.config/starship/kali.toml
    run ln -sf $rootdir/items/starship/src/lingshinx.toml ~/.config/starship/lingshinx.toml
    run ln -sf $rootdir/items/starship/src/thirdwinter.toml ~/.config/starship/thirdwinter.toml
    run ln -sf $rootdir/items/starship/src/tokyo_night.toml ~/.config/starship/tokyo_night.toml
    run ln -sf $rootdir/items/starship/src/catppuccin.toml ~/.config/starship/catppuccin.toml
}

# Check if the item is installed, return true if installed
function check() {
    [[ -L ~/.config/starship.toml || -f ~/.config/starship.toml ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/starship.toml
    run rm -rf ~/.config/starship
}
