#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        mdfind "kMDItemFSName == '*.app'" | grep Ghostty 2>/dev/null 1>&2
        return $(( $? ))
    elif [[ $(uname) == "Linux" ]]; then
        command -v ghostty >/dev/null 2>&1 && return 0
        return 0
    else
        log_error "Unsupported system"
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "helium" ]]; then
        run curl -L https://github.com/ghostty-org/ghostty/releases/download/tip/Ghostty.dmg -o /tmp/Ghostty.dmg
        run open /tmp/Ghostty.dmg
    elif [[ $sys_id == "hydrogen" ]]; then
        run paru -S ghostty
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/ghostty
    run ln -sfn $rootdir/items/ghostty/src/shaders $HOME/.config/ghostty/shaders
    run ln -sfn $rootdir/items/ghostty/src/themes  $HOME/.config/ghostty/themes
    if [[ $sys_id == "hydrogen" ]]; then
        log_hint "Gnerating config file..."
        run "awk -f $rootdir/utils/replace.awk $rootdir/items/ghostty/src/local/$sys_id.awk $rootdir/items/ghostty/src/config.tmpl | tee ~/.config/ghostty/config"
        return $(( $? ))
    elif [[ $sys_id == "helium" ]]; then
        log_hint "Gnerating config file..."
        run "gawk -f $rootdir/utils/replace.awk $rootdir/items/ghostty/src/local/$sys_id.awk $rootdir/items/ghostty/src/config.tmpl | tee ~/.config/ghostty/config"
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/ghostty ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/ghostty
}
