#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [ $(uname) != "Darwin" ]; then
        log_error "Cannot install Karabiner on os except MacOS"
        return 1
    fi
    mdfind "kMDItemFSName == '*.app'" | grep Karabiner 2>/dev/null 1>&2
    if [[ $? == 0 ]]; then
        return 0
    else
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    run brew install karabiner-elements
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/karabiner
    run ln -sf $rootdir/items/karabiner/src/karabiner.json ~/.config/karabiner/karabiner.json
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/karabiner ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/karabiner/karabiner.json
}
