#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v lsd >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    case "$sys_id" in
        "hydrogen")
            run paru -S lsd
            return $(( $? ))
            ;;
        "lithium")
            run apt install lsd
            return $(( $? ))
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/lsd
    items=$(bash -c "ls $rootdir/items/lsd/src")
    for item in $items; do
        run ln -sfn $rootdir/items/lsd/src/$item ~/.config/lsd/$item
    done
    log_hint "please run 'ln -sf ~/.config/lsd/themes/<theme>.yaml ~/.config/lsd/colors.yaml' to choose a theme"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/lsd ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/lsd
}
