#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v lsd >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run sudo pacman -S lsd
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/lsd/src ~/.config/lsd
    log_hint "please run 'ln -sf ~/.config/lsd/themes/<theme>.yaml ~/.config/lsd/colors.yaml' to choose a theme"
    # run cd ~/.config/lsd
    # run ln -sf themes/CatppuccinMocha.yaml colors.yaml
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/lsd ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run [[ -L ~/.config/lsd ]] && unlink ~/.config/lsd
}
