#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v waybar >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S waybar
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/waybar
    run ln -sfn $rootdir/items/waybar/src/config.jsonc ~/.config/waybar/config.jsonc
    run ln -sfn $rootdir/items/waybar/src/style.css ~/.config/waybar/style.css
    run ln -sfn $rootdir/items/waybar/src/scripts ~/.config/waybar/scripts
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/waybar ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/waybar
}
