#!/usr/bin/env bash

# This is a patch for git config, provides a patch for git config

# Check the dependency return false if installed dependency
function check_dep() {
    return 0
}

# Things to do to install the dependency
function install_dep() {
    :;
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/gitignore/src/gitignore $HOME/.gitignore
    run git config --global core.excludesfile $HOME/.gitignore
}

# Check if the item is installed, return false if installed
function check() {
    [[ -f $HOME/.gitignore ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm $HOME/.gitignore
}
