#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v zathura >/dev/null 2>&1 && return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    run paru -S zathura
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/zathura
    run ln -sfn $rootdir/items/zathura/src/zathurarc ~/.config/zathura/zathurarc
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d $HOME/.config/zathura ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/zathura
}
