#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v wezterm >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        run paru -S wezterm
    elif [[ $sys_id == "helium" ]]; then
        run brew install wezterm
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/wezterm
    run ln -sf $rootdir/items/wezterm/src/wezterm.lua ~/.config/wezterm/wezterm.lua
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/wezterm ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/wezterm
}
