#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v wezterm >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    :;
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/wezterm
    run ln -sf $rootdir/items/src/wezterm/wezterm.lua ~/.config/wezterm/wezterm.lua
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/wezterm ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    :;
}
