#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        pacman -Q rofi >/dev/null 2>&1
        return $(( $? ))
    else
        log_error "No package manager is assigned"
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run sudo paru -S rofi
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/rofi/src ~/.config/rofi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/rofi ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/rofi
}
