#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        pacman -Q rofi-wayland
        return $(( !$? ))
    else
        log_error "No package manager is assigned"
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run sudo paru -S rofi-wayland
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/rofi/src ~/.config/rofi
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/rofi ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/rofi
}
