#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v hyprlock >/dev/null 2>&1 || pacman -Q ttf-fira-code >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    pacman -Q hyprlock  >/dev/null 2>&1 || run paru -S hyprlock
    pacman -Q ttf-fira-code >/dev/null 2>&1 || run paru -S ttf-fira-code
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/hypr/scripts/hyprlock
    run ln -sfn $rootdir/items/hyprlock/src/hyprlock.conf ~/.config/hypr/hyprlock.conf
    run ln -sfn $rootdir/items/hyprlock/src/scripts/status.sh ~/.config/hypr/scripts/hyprlock/status.sh
}

# Check if the item is installed, return true if installed
function check() {
    [[ -f $HOME/.config/hypr/hyprlock.conf && -f $HOME/.config/hypr/scripts/hyprlock/status.sh ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm $HOME/.config/hypr/hyprlock.conf 
    run rm $HOME/.config/hypr/scripts/hyprlock/status.sh
}
