#!/usr/bin/env bash

has_autoconf=0
has_automake=0
has_quickshell=0

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v autoreconf >/dev/null 2>&1; then
        has_autoconf=1
    else
        log_hint "autoconf not installed"
    fi
    if command -v aclocal >/dev/null 2>&1; then
        has_automake=1
    else
        log_hint "automake not installed"
    fi
    if command -v quickshell >/dev/null 2>&1; then
        has_quickshell=1
    else
        log_hint "quickshell not installed"
    fi
    if [[ $has_automake -eq 1 && $has_autoconf -eq 1 && $has_quickshell -eq 1 ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) != "Linux" ]]; then
        log_error "Cannot install quickshell on non-linux environment"
        return 1
    fi
    if [[ $sys_id == "archlinux" ]]; then
        [[ $has_autoconf -eq 0 ]] && run paru -S autoconf
        [[ $has_automake -eq 0 ]] && run paru -S automake
        [[ $has_quickshell -eq 0 ]] && run paru -S quickshell
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ $sys_id == "archlinux" ]]; then
        run ln -sf $rootdir/items/quickshell/src ~/.config/quickshell
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/quickshell ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/quickshell
}
