#!/usr/bin/env bash

declare -A DEPS=(
    [autoconf]="autoreconf:autoconf"
    [automake]="aclocal:automake"
    [quickshell]="quickshell:quickshell"
)

declare -A HAS

# Check the dependency return true if installed dependency
function check_dep() {
    local all_ok=1
    for dep in "${!DEPS[@]}"; do
        local cmd="${DEPS[$dep]%%:*}"
        if command -v "$cmd" >/dev/null 2>&1; then
            HAS[$dep]=1
        else
            HAS[$dep]=0
            all_ok=0
            log_hint "'$dep' not installed"
        fi
    done
    return $(( !$all_ok ))
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) != "Linux" ]]; then
        log_error "Cannot install quickshell on non-linux environment"
        return 1
    fi
    if [[ $sys_id == "archlinux" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]##*:}"
            [[ ${HAS[$dep]} -eq 0 ]] && run paru -S "$pkg"
        done
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    if [[ $sys_id == "archlinux" ]]; then
        run ln -sfn $rootdir/items/quickshell/src ~/.config/quickshell
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/quickshell ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/quickshell
}
