#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v tmux >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    case "$sys_id" in
        "hydrogen")
            run paru -S tmux
            return $(( $? ))
            ;;
        "helium")
            run brew install tmux
            return $(( $? ))
            ;;
        "lithium")
            run apt install tmux
            return $(( $? ))
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/tmux/plugins
    run ln -sf $rootdir/items/tmux/src/tmux.conf ~/.config/tmux/tmux.conf
    run git clone --recursive --depth 1 --branch master https://github.com/tmux-plugins/tpm.git ~/.config/tmux/plugins/tpm
    log_hint "Please run 'tmux', then press prefix-i to install plugins"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/tmux ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/tmux
}
