#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    return 0
}

# Things to do to install the dependency
function install_dep() {
    :;
}

# Things to do to install the item
function install() {
    run mkdir -p ~/.config/tmux/plugins
    run ln -sf $rootdir/items/tmux/src/tmux.conf ~/.config/tmux/tmux.conf
    run git clone --recursive --depth 1 --branch master https://github.com/tmux-plugins/tpm.git ~/.config/tmux/plugins/tpm
    color_echo MAGENTA "Notice: Please run 'tmux', then press prefix-i to install plugins"
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/tmux ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    :;
}
