#!/usr/bin/env bash

HAS_ALACRITTY=0
HAS_FONT=0

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        mdfind "kMDItemFSName == '*.app'" | grep Alacritty 2>/dev/null 1>&2
        return $(( $? ))
    elif [[ $(uname) == "Linux" ]]; then
        command -v alacritty >/dev/null 2>&1 || return 1
        HAS_ALACRITTY=1
        fc-list | grep "ComicCode Nerd Font Medium" >/dev/null 2>&1 || return 1
        HAS_FONT=1
        return 0
    else
        log_error "Unsupported system"
        return 1
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        [[ $HAS_ALACRITTY -eq 0 ]] && {
            run paru -S alacritty-graphics 
            [[ $? -ne 0 ]] && log_error "Cannot install alacritty" && return 1
        }
        [[ $HAS_FONT -eq 0 ]] && {
            run mkdir -p $HOME/.local/share/fonts/
            run 7z x $rootdir/assets/fonts/ComicCodeNerdFont.7z -o$HOME/.local/share/fonts
            run fc-cache -fv
            [[ $? -ne 0 ]] && log_error "Cannot install fonts" && return 1
        }
        return 0
    elif [[ $sys_id == "macmini" ]]; then
        run curl -L https://github.com/ayosec/alacritty/releases/download/v0.15.1-graphics/Alacritty-v0.15.1-graphics.dmg -o /tmp/alacritty.dmg
        run open /tmp/alacritty.dmg
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run mkdir -p $HOME/.config/alacritty
    run ln -sfn $rootdir/items/alacritty/src/color-scheme $HOME/.config/alacritty/color-scheme
    if [[ $sys_id == "archlinux" ]]; then
        log_hint "Gnerating config file..."
        run "awk -f $rootdir/utils/replace.awk $rootdir/items/alacritty/src/local/$sys_id.awk $rootdir/items/alacritty/src/alacritty.toml.tmpl | tee ~/.config/alacritty/alacritty.toml"
        return $(( $? ))
    elif [[ $sys_id == "macmini" ]]; then
        log_hint "Gnerating config file..."
        run "gawk -f $rootdir/utils/replace.awk $rootdir/items/alacritty/src/local/$sys_id.awk $rootdir/items/alacritty/src/alacritty.toml.tmpl | tee ~/.config/alacritty/alacritty.toml"
        return $(( $? ))
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/alacritty ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/alacritty
}
