#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run pacman -Q alacritty-graphics
    fi
    return $(( !$? ))
}

# Things to do to install the dependency
function install_dep() {
    :;
}

# Things to do to install the item
function install() {
    if [[ $sys_id == "archlinux" ]]; then
        run ln -sf $rootdir/items/alacritty/src ~/.config/alacritty
    fi
}

# Check if the item is installed, return true if installed
function check() {
    if [[ $sys_id == "archlinux" ]]; then
        if [[ -d ~/.config/alacritty ]]; then
            return 1
        else
            return 0
        fi
    fi
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    :;
}
