#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ $(uname) == "Darwin" ]]; then
        mdfind "kMDItemFSName == '*.app'" | grep Alacritty 2>/dev/null 1>&2
        return $(( !$? ))
    elif [[ $(uname) == "Linux" ]]; then
        command -v alacritty >/dev/null 2>&1
        return $(( !$? ))
    else
        log_error "Unsupported system"
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S alacritty-graphics
        return $(( $? ))
    elif [[ $sys_id == "macmini" ]]; then
        run curl -L https://github.com/ayosec/alacritty/releases/download/v0.15.1-graphics/Alacritty-v0.15.1-graphics.dmg -o /tmp/alacritty.dmg
        run open /tmp/alacritty.dmg
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sfn $rootdir/items/alacritty/src ~/.config/alacritty
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/alacritty ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.config/alacritty
}
