#!/usr/bin/env bash

# Check the dependency return false if installed dependency
function check_dep() {
    return 0
}

# Things to do to install the dependency
function install_dep() {
    return 0
}

# Things to do to install the item
function install() {
    if [[ $(uname) == "Darwin" ]]; then
        run mkdir -p $HOME/Library/Fonts
        run 7z x $rootdir/assets/fonts/ComicCodeNerdFont.7z -o$HOME/Library/Fonts
        [[ $? -ne 0 ]] && log_error "Cannot install fonts" && return 1
        return 0
    elif [[ $(uname) == "Linux" ]]; then
        run mkdir -p $HOME/.local/share/fonts/
        run 7z x $rootdir/assets/fonts/ComicCodeNerdFont.7z -o$HOME/.local/share/fonts
        run fc-cache -fv
        [[ $? -ne 0 ]] && log_error "Cannot install fonts" && return 1
        return 0
    else
        log_error "Unsupported system"
        return 1
    fi
}

# Check if the item is installed, return false if installed
function check() {
    if [[ $(uname) == "Darwin" ]]; then
        [[ -d $HOME/Library/Fonts/ComicCode ]] && return 0
        return 1
    elif [[ $(uname) == "Linux" ]]; then
        fc-list | grep "ComicCode Nerd Font Medium" >/dev/null 2>&1 && return 0
        return 0
    else
        log_error "Unsupported system"
        return 1
    fi
}

# Things to do to uninstall the item
function uninstall() {
    if [[ $(uname) == "Darwin" ]]; then
        [[ -d $HOME/Library/Fonts/ComicCode ]] && run rm -rf $HOME/Library/Fonts/ComicCode
        return 1
    elif [[ $(uname) == "Linux" ]]; then
        run rm -rf $HOME/.local/share/fonts
    else
        log_error "Unsupported system"
        return 1
    fi
}
