#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v qq 1>/dev/null 2>&1 && return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S linuxqq-nt-bwrap
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/linuxqq/src/qq-bwrap-flags.conf $HOME/.config/qq-bwrap-flags.conf
    run ln -sf $rootdir/items/linuxqq/src/qq-electron-flags.conf $HOME/.config/qq-electron-flags.conf
}

# Check if the item is installed, return true if installed
function check() {
    [[ -f $HOME/.config/qq-bwrap-flags.conf && -f $HOME/.config/qq-electron-flags.conf ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm $HOME/.config/qq-bwrap-flags.conf 
    run rm $HOME/.config/qq-electron-flags.conf
}
