#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v mpv >/dev/null 2>&1 && return 1
    return 0
}

# Things to do to install the dependency
function install_dep() {
    run paru -S mpv
}

# Things to do to install the item
function install() {
    items=$(bash -c "ls $rootdir/items/mpv/src")
    run mkdir -p ~/.config/mpv
    for item in $items; do
        run ln -sfn $rootdir/items/mpv/src/$item ~/.config/mpv/$item
    done
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/mpv ]] && return 1
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/mpv
}
