#!/usr/bin/env bash

has_nvim=0
has_yarn=0
has_make=0
has_npm=0
has_unzip=0

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v nvim >/dev/null 2>&1; then
        has_nvim=1
    else
        log_hint "nvim not installed"
    fi
    if command -v yarn >/dev/null 2>&1; then
        has_yarn=1
    else
        log_hint "yarn not installed"
    fi
    if command -v make >/dev/null 2>&1; then
        has_make=1
    else
        log_hint "make not installed"
    fi
    if command -v npm >/dev/null 2>&1; then
        has_npm=1
    else
        log_hint "npm not installed"
    fi
    if command -v unzip >/dev/null 2>&1; then
        has_unzip=1
    else
        log_hint "unzip not installed"
    fi
    if [[ $has_nvim -eq 1 && $has_yarn -eq 1 && $has_yarn -eq 1 && $has_npm -eq 1 && $has_unzip -eq 1 ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        [[ $has_nvim -eq 0 ]] && run paru -S nvim
        [[ $has_yarn -eq 0 ]] && run paru -S yarn
        [[ $has_make -eq 0 ]] && run paru -S make
        [[ $has_npm  -eq 0 ]] && run paru -S npm
        [[ $has_unzip  -eq 0 ]] && run paru -S unzip
    elif [[ $sys_id == "macmini" ]]; then
        [[ $has_nvim -eq 0 ]] && run brew install nvim
        [[ $has_yarn -eq 0 ]] && run brew install yarn
        [[ $has_make -eq 0 ]] && run brew install make
        [[ $has_npm  -eq 0 ]] && run brew install npm
        [[ $has_unzip  -eq 0 ]] && run brew install unzip
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    log_warn "Using http connection to pull nvim config repo, please check ssh accession"
    run git clone --branch main https://github.com/aurora0x27/nvim-config ~/.config/nvim
    log_hint "Please use these commands to change to ssh access"
    log_hint "git remote remove origin"
    log_hint "git remote add origin git@github.com:aurora/nvim-config.git"
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -d ~/.config/nvim ]]; then
        return 1
    else
        return 0
    fi
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/nvim
}
