#!/usr/bin/env bash

# [<package desc>]="<binary>:<package name>"
declare -A DEPS=(
    [nvim]="nvim:neovim"
    [yarn]="yarn:yarn"
    [make]="make:make"
    [npm]="npm:npm"
    [unzip]="unzip:unzip"
    [ripgrep]="rg:ripgrep"
    [tinymist]="tinymist:tinymist"
    [websocat]="websocat:websocat"
)

declare -A HAS

# Check the dependency return true if installed dependency
function check_dep() {
    local all_ok=1
    for dep in "${!DEPS[@]}"; do
        local cmd="${DEPS[$dep]%%:*}"
        if command -v "$cmd" >/dev/null 2>&1; then
            HAS[$dep]=1
        else
            HAS[$dep]=0
            all_ok=0
            log_hint "'$dep' not installed"
        fi
    done
    return $(( !$all_ok ))
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "hydrogen" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]##*:}"
            [[ ${HAS[$dep]} -eq 0 ]] && run paru -S "$pkg"
        done
    elif [[ $sys_id == "helium" ]]; then
        for dep in "${!DEPS[@]}"; do
            local pkg="${DEPS[$dep]##*:}"
            [[ ${HAS[$dep]} -eq 0 ]] && run brew install "$pkg"
        done
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    log_warn "Using http connection to pull nvim config repo, please check ssh accession"
    run git clone --branch main https://github.com/aurora0x27/nvim-config ~/.config/nvim
    log_hint "Please use these commands to change to ssh access"
    log_hint "git remote remove origin"
    log_hint "git remote add origin git@github.com:aurora/nvim-config.git"
    run "ln -sfn $rootdir/$target/src/$sys_id.nvimrc.json ~/.config/nvim/nvimrc.json"
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/nvim ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/nvim
}
