#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if command -v nvim >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    if [[ $sys_id == "archlinux" ]]; then
        run sudo pacman -S nvim
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    run git clone --branch main git@github.com:aurora0x27/nvim-config ~/.config/nvim
}

# Check if the item is installed, return true if installed
function check() {
    if [[ $sys_id == "archlinux" ]]; then
        if [[ -d ~/.config/nvim ]]; then
            return 1
        else
            return 0
        fi
    fi
    return 0
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/nvim
}
