#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    if [[ -d ~/.oh-my-bash ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to install the dependency
function install_dep() {
    # Unsafe command
    run 'bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"'
    run mv ~/.bashrc ~/.bashrc.default
}

# Things to do to install the item
function install() {
    run ln -sf $rootdir/items/bash/src/bash.conf.sh ~/.bashrc
}

# Check if the item is installed, return true if installed
function check() {
    if [[ -L ~/.bashrc ]]; then
        return 1
    else
        return 0
    fi
}

# Things to do to uninstall the item
function uninstall() {
    run unlink ~/.bashrc
}
