#!/usr/bin/env bash

# Check the dependency return false if installed dependency
check_dep() {
    command -v xdg-user-dirs-update 1>/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
install_dep() {
    case "$sys_id" in
        hydrogen)
            run paru -S xdg-user-dirs
            ;;
        *)
            log_error "No default installation method is set"
            return 1
            ;;
    esac
}

# Things to do to install the item
install() {
    run mkdir -p ~/.config

    run ln -sfn "$item_dir/src/user-dirs.dirs" ~/.config/user-dirs.dirs
    run ln -sfn "$item_dir/src/user-dirs.locale" ~/.config/user-dirs.locale

    run xdg-user-dirs-update
}

# Check if the item is installed, return false if installed
check() {
    [[ -f ~/.config/user-dirs.dirs && -f ~/.config/user-dirs.locale ]] && return 0
    return 1
}

# Things to do to uninstall the item
uninstall() {
    run rm -f ~/.config/user-dirs.{dirs,locale}
}
