#!/usr/bin/env bash

# Check the dependency return true if installed dependency
function check_dep() {
    command -v anyrun >/dev/null 2>&1 && return 0
    return 1
}

# Things to do to install the dependency
function install_dep() {
    if [[ $(uname) != "Linux" ]]; then
        log_error "Cannot install anyrun on none-linux system"
        return 1
    fi
    if [[ $sys_id == "archlinux" ]]; then
        run paru -S anyrun-git
    else
        log_error "No default installation method is set"
        return 1
    fi
}

# Things to do to install the item
function install() {
    items=$(bash -c "ls $rootdir/items/anyrun/src")
    run mkdir -p ~/.config/anyrun
    for item in $items; do
        run ln -sfn $rootdir/items/anyrun/src/$item ~/.config/anyrun/$item
    done
}

# Check if the item is installed, return true if installed
function check() {
    [[ -d ~/.config/anyrun ]] && return 0
    return 1
}

# Things to do to uninstall the item
function uninstall() {
    run rm -rf ~/.config/anyrun
}
